---

- name: Import PVWA SSL certificate into PSM
  ansible.builtin.include_tasks: import_pvwa_certificate.yml

- include_role:
    name: psm
  vars:
    psm_extract: true
    psm_prerequisites: true
    psm_install: true
    psm_postinstall: true
    psm_hardening: true
    psm_registration: false
    psm_official: false
